app = 'minceraft'
primary_region = 'syd'

[env]
  ALLOW_FLIGHT = true
  AUTOSTOP_TIMEOUT_EST = 300 # seconds
  AUTOSTOP_TIMEOUT_INIT = 300 # seconds
  DIFFICULTY = "hard"
  ENABLE_AUTOSTOP = true
  ENABLE_COMMAND_BLOCK = true
  EULA = true
  ICON = "https://cdn.discordapp.com/icons/142499246430486528/b3c8381a61e36f17da7cd3545076d4c5.webp"
  MAX_WORLD_SIZE = 12288
  MEMORY = "3G"
  MOTD = "A land down under"
  OPS = "39f4d0d2-197b-494a-a3b4-252c24b7d124"
  PLAYER_IDLE_TIMEOUT = 30 # min
  RCON_PASSWORD = "282275254842afb1bb2c1d995afc87a75b4b9fac0cfd3fe0f8ddf79d06bfced8"
  SEED = "-7133067522529993669"
  SERVER_NAME = "Minceraft Server"
  SNOOPER_ENABLED = false
  SPAWN_PROTECTION = 0
  TZ = "Australia/Sydney"
  USE_AIKAR_FLAGS = true
  VANILLATWEAKS_SHARECODE = "bViW4M,Ta0hEj,mExaU4"
  VERSION = "1.21.4"
  VIEW_DISTANCE = 32
  WHITELIST = "AkiraYasha,Argus_Velodon,assassinator98,BRMixer,Captian_Gingarr,charlese2,DesktopTv,Hamsterdrive,Himatron,lazy_gamer,lolwerty,Luwilightxoxo,Nahtan1305,Smallsey4,UNIXKernalPanic,Weltherrschaft,widge42,Xx_Pyrotonic_xX,Yggdrasl,ZAdogZ"

[build]
  image = "itzg/minecraft-server:latest"

[[services]]
  internal_port = 25565
  protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = true
  [[services.ports]]
    port = 38975
  [[services.tcp_checks]]
    grace_period = "30s"

[[services]]
  internal_port = 25575
  protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = false
  [[services.ports]]
    port = 33205
  [[services.tcp_checks]]
    grace_period = "30s"

[[vm]]
  memory = "4GB"
  cpus = 2
  cpu_kind = "performance"

[mounts]
  source = "minceraft"
  destination = "/data"
  initial_size = "1GB"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "100GB"
