app = 'minceraft'
primary_region = 'syd'

[env]
  ALLOW_FLIGHT = true
  AUTOSTOP_TIMEOUT_EST = 300 # seconds
  AUTOSTOP_TIMEOUT_INIT = 300 # seconds
  DIFFICULTY = "hard"
  ENABLE_AUTOSTOP = true
  ENABLE_COMMAND_BLOCK = false
  EULA = true
  ICON = "https://cdn.discordapp.com/icons/142499246430486528/b3c8381a61e36f17da7cd3545076d4c5.webp"
  JVM_XX_OPTS = "-XX:MaxRAMPercentage=75"
  MAX_WORLD_SIZE = 12288
  MEMORY = ""
  MOTD = "A land down under"
  PLAYER_IDLE_TIMEOUT = 30 # min
  RESOURCE_PACK = "https://cdn.aidan.pro/minecraft/VanillaTweaks_r613065_MC1.21.x.zip"
  SEED = "-7133067522529993669"
  SERVER_NAME = "Minceraft Server"
  SNOOPER_ENABLED = false
  SPAWN_PROTECTION = 0
  TZ = "Australia/Sydney"
  USE_AIKAR_FLAGS = true
  VANILLATWEAKS_SHARECODE = "4RJNOu,bTZx2n"
  VERSION = "1.21.4"
  VIEW_DISTANCE = 32

[build]
  image = "itzg/minecraft-server:latest"

[[services]]
  internal_port = 25565
  protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = true
  [[services.ports]]
    port = 38975
  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "300s"

[[services]]
  internal_port = 25575
  protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = false
  [[services.ports]]
    port = 33205
  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "300s"

[[vm]]
  memory = "8GB"
  cpus = 4
  cpu_kind = "performance"

[mounts]
  source = "minceraft"
  destination = "/data"
  initial_size = "1GB"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "100GB"
